# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: jax-demo
  context: jax-demo # jax-demo folder
  dockerfile: ./Dockerfile

spec:
  operator: jax
  image: jax-demo
  command: "python3 -u /app/main.py"
  tensorboard:
    enabled: true
  types:
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
