# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: pytorch-demo
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: image
  command: "python3 src/main.py"

  tensorboard:
    enabled: true

  types:
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

